### ISSUE TITLE
[Suggestion] Use markdown for /docs

### ISSUE THREAD

**Issue by jakecleary** [thekabal/tki#11]
I propose we format the contents of `/docs` to use markdown. This would allow the documents to be structured better and would have the added benefit of github and various other services formatting them automatically.

Also, changing the file extensions to `.md` wont break plaintext readers so there's no real negative impact with this change.

I'm happy to change these for you too!

**Comment by thekabal** [comment]
I'm totally on board for that change. Feel free!

**Comment by thekabal** [comment]
PR merged! Great work, Sir!
