### ISSUE TITLE
Extend PDO to properly include a prefix property

### ISSUE THREAD

**Issue by thekabal** [thekabal/tki#13]
Extend PDO to properly include a prefix property. Right now, we apply the property despite it not being included in PDO. Extending the PDO class with a class like:

https://gist.github.com/gfabrizi/7282782
or
http://stackoverflow.com/questions/5175357/extending-pdo-class

Would eliminate a class of bugs identified by Scrutinizer that are currently filtered.

**Comment by jakecleary** [comment]
This sounds smart to me, and would give us the opportunity to start encapsulating any other repetitive database setup code.
