### ISSUE TITLE
setup_info.php cookie test fails

### ISSUE THREAD

**Issue by razermackham** [thekabal/tki#52]
Upon opening setup_info.php for the first time. The cookie test fails. And the link in the failure message (https://kabal-invasion.com/forums/) is no longer valid. After a page refresh the test passes. Perhaps the failure message should be updated to suggest refreshing, and change the forums link to github?

Notice: Undefined index: TestCookie in /var/www/html/tki/setup_info.php on line 101

Cookie Test	Failed! - Cookies cannot be set. Please report this issue to [The TKI Forums](https://kabal-invasion.com/forums/)

**Comment by thekabal** [comment]
I'm not a fan of the cookie test. To fix it will require some serious recoding. In the meantime, the feedback about the link and the suggestion to users is noted, and I'll commit a fix for that now.
