### ISSUE TITLE
setup_info.php smarty path test fails

### ISSUE THREAD

**Issue by razermackham** [thekabal/tki#53]
Smarty path Test	Failed! - Smarty is not installed in the correct location - please install it at vendor/smarty/smarty/

The path searched for is "vendor/smarty/smarty/distribution/libs/Smarty.class.php"
The correct path is          "vendor/smarty/smarty/libs/Smarty.class.php"

**Comment by thekabal** [comment]
Great catch, thank you for the bug report. I had not updated setup_info for the new setup, so this helped remind me!
