### ISSUE TITLE
lost files

### ISSUE THREAD

**Issue by lotu5david** [thekabal/tki#62]
require_once(./vendor/autoload.php): failed to open stream: No such file or directory in D:\WWW\tki-develop\common.php on line 19

**Comment by thekabal** [comment]
Hello, as mentioned in the docs/ directory, TKI is not supported on Windows/IIS. Out of curiosity, which versions of Windows & IIS were you trying to install/run it on?

**Comment by lotu5david** [comment]
i use winserver2008 & apache .not the IIS.

**Comment by thekabal** [comment]
Windows is not supported at this time (but patches are welcome!)
