### ISSUE TITLE
Where is this hosted?

### ISSUE THREAD

**Issue by jakecleary** [thekabal/tki#7]
Hey,

I can't find where to test this out. I'm potentially interested in contributing but I'd rather have a play before I get stuck into any code.

Thanks in advance 😄

**Comment by thekabal** [comment]
Greetings!

I don't currently have a game running, but plan to have a hosted game setup in the next few months. I'm targetting an October release, and will likely have the game up by then.

**Comment by jakecleary** [comment]
Hey!

Okay great. I'm having some issues setting up the project locally (see #8). Mind giving me a hand?
