### ISSUE TITLE
[Suggestion] Think about using git flow

### ISSUE THREAD

**Issue by jakecleary** [thekabal/tki#9]
I'm looking to contribute some change to the repo but in order to avoid stepping on each other I think it might be worth using [git flow](http://danielkummer.github.io/git-flow-cheatsheet/), or some other documented methodology.

**In short, the following changes would have to be made**
- Add a new `develop` branch, this will act as the main branch and the one shown when the project is loaded on github.
- All new work would be done on `feature/{feature-name}` branches, branched from `develop`.
- All new work would be merged into `develop` (or via a pull request for contributors).
- New releases (major build milestones, official public releases) are merged into `master` and tagged appropriately using [semver](http://semver.org/).

This kind of methodology is used a lot in the wild, and personally it has improved my workflow hugely when working on large scale projects _and_ open source projects where reliability is desired.

I'd be happy to explain it in further detail, and help you set it up if required. I use it daily at work and it's been very helpful to our team; I think you'll like it.

**Comment by thekabal** [comment]
I'm OK with adding a feature branch, and encourage you to do so when submitting PR's.

The rest, less so. I don't see the value in having develop & then feature branched from that. What does that provide that branching feature from master does not? I welcome the discussion.

But Semver is a total non-starter. We do not have an API yet, and won't even be close to that until the Adodb->PDO conversion AND the Smarty template work is complete - both are easily months away at best. Until then, Semver literally makes no logical sense to use.

**Comment by jakecleary** [comment]
Hey dude,

Yeah that makes sense. You're definitely right about semver, right now the project isn't being used anyway right? I'm being premature, apologies!

The only reason I suggest using a develop/master pair is that it makes it quite clear what it a release and what's "in development". It's not 100% necessary, but it definitely adds some clarity. If you're not keen that's totally fine!

I'll use feature branches for any PRs I submit and we'll keep it at that! Thanks for getting back to me.

**Comment by jakecleary** [comment]
@thekabal I see you've added a `develop` branch… are you wanting to start working from that now? The idea is that we branch-from and merge-into `develop` and then merge `develop` into `master` when you want to tag a release. I only ask because you're still making commits to `master`, and I just want to know what branch you want me to branch off from. If you want to start doing that, it's worth setting `develop` as the branch that github shows on the project page by default, to highlight it's use and discourage people from thinking the latest commits can be used as a "release".
